### ISSUE TITLE
Compilation error, apprently the setter seems to be removed.

### ISSUE THREAD

**Issue by sajjadpz** [Berberer/SurniaQA#1]
https://github.com/dice-group/SurniaQA/blob/336b06b3f98d19411519577aeff591f72756bd42/src/main/java/de/upb/ds/surnia/qa/AbstractQuestionAnswerer.java#L117

Apparently the setter `setAnswerAsQALDJSON` has been removed from the `Question` class which is coming from `org.aksw.qa.commons.datastructure.Question;`

@RicardoUsbeck can you please have a look.

**Comment by RicardoUsbeck** [comment]
@SiC42 can you make a merge of your branch with the master please?

**Comment by SiC42** [comment]
I'm not yet finished with my branch, as I have to restructure some things.
However, the issue can be fixed by changing the library to ".18".
This seems to be an error on the org.aksw.qa.commons.datastructure.Question btw @RicardoUsbeck.
The commit with the ".16"-tag has the above mentioned method, but the release on mvn does not.

**Comment by RicardoUsbeck** [comment]
Any estimate on the finish date?

**Comment by SiC42** [comment]
Depends on what you want. I almost finished implementing Autoindex in a very raw way.
I should at least write tests. After that we probably should chat if this is the way you intended it or if you want some more refined processing.
